### PR TITLE
Use BooleanAdjacencyMatrixMutableCopy in IsHamiltonianDigraph

### LINKED ISSUE #191: IsHamiltonianDigraph attempts to modify immutable blists
As highlighted in [a recent handy Travis CRON job](https://travis-ci.org/gap-packages/Digraphs/jobs/518250507), `IsHamiltonianDigraph` modifies mutable lists. This would mean that the attribute `BooleanAdjacencyMatrix` would potentially by modified by running `IsHamiltonianDigraph`. That this didn't previously raise an error was a bug in GAP, which has just been fixed in GAP master branch in https://github.com/gap-system/gap/pull/3392. Now we get the following error:
```
gap> g := Digraph([[3], [3], [1, 2]]);
<digraph with 3 vertices, 4 edges>
gap> IsHamiltonianDigraph(g);
Error, IntersectBlist: <blist1> must be a mutable boolean list (not a list (boolean,imm)) in
  IntersectBlist( tempblist, adjmatrix[j] );
```

### PR DESCRIPTION
**Pull request by wilfwilson**
Resolves #191.

### CODE REVIEW

**Comment by wilfwilson** [comment]
I have no idea why the AppVeyor build keeps failing; on my fork it works fine: https://ci.appveyor.com/project/wilfwilson/digraphs/builds/23740979

**Comment by wilfwilson** [comment]
In fact, one time on my fork it did fail https://ci.appveyor.com/project/wilfwilson/digraphs/builds/23740935

It must just be weirdness with AppVeyor. I've had 5 AppVeyor builds run for this PR, all with the exact same one-line change; 2 passed and failed. There is no way that the change in this PR could have caused those failures. So I propose that we ignore this. If AppVeyor continues to play up, then we should get rid of it.

**Comment by james-d-mitchell** [comment]
I've restarted the build, hopefully it'll just pass...

**Comment by wilfwilson** [comment]
Thanks @james-d-mitchell, I'm unable to restart the builds myself.

**Comment by james-d-mitchell** [comment]
If not, I agree we should ignore it

**Comment by wilfwilson** [comment]
It passed this time :)

**Comment by james-d-mitchell** [comment]
Awesome, clearly the right thing to do.

**Pull request merged**
