### PR TITLE
ci: use azure pipelines

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This is a first approximation of how to do the CI using azure pipelines, and docker. I don't have any preference for azure pipelines over github actions, but I couldn't figure out how to get docker containers to work using github actions (see https://github.com/libsemigroups/libsemigroups/issues/254), and I could figure that out using azure pipelines. The advantage of doing it with a docker container is: that it's possible to ensure that the CI is set up and will run locally (which is faster than waiting for some remote jobs to fail repeatedly); the building of GAP is completely separate (and nicely encapsulated).

There are some issues:

1. The gap-docker container only supports the "latest" tag, and so it isn't currently possible to specify which version of GAP is used inside the container. This would be trivial to fix for the maintainer of:

https://hub.docker.com/r/gapsystem/gap-docker/

I don't know if @alex-konovalov might be interested in supporting this feature, or allowing me access to the docker hub account so that I can enable it? For example, we are doing this with the `libsemigroups` docker container here:

https://hub.docker.com/r/libsemigroups/libsemigroups-docker/tags

2. There's currently only one job, it should be easy enough to scale this to the original jobs that we ran on travis once issue 1 is fixed. 

3. I think I probably broke the CI scripts support for appveyor.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Another issue is that I don't have sufficient permissions in the gap-packages organisation to enable azure pipelines for `Digraphs`, can someone @fingolfin, @alex-konovalov, @wilfwilson who has sufficient access please enable this? This should only involve a few clicks, for example:

https://dev.azure.com/jdm3/jdm3/_build/results?buildId=21&view=results

**Comment by fingolfin** [comment]
Last I looked at it, Azure Pipelines required write access to repositories, so I don't want to enable it globally. But if you still want it, can do it for the listed repos

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin, I can't really see any problem with enabling write access for azure pipelines, so yes please, go ahead and enable it for gap-packages/digraphs.

**Comment by fingolfin** [comment]
Done

**Comment by james-d-mitchell** [comment]
Thanks! @fingolfin

**Comment by james-d-mitchell** [comment]
Sorry to be a pain, but I'm struggling to find where I can access the azure pipeline thing that you've enabled @fingolfin, any chance you could post a link?

**Comment by fingolfin** [comment]
I added "Azure Pipelines" from the market place to the `gap-packages` org and activate it for the `Digraphs` repository. Which then tried to force me to create a MSN account, but after I bailed out, it still said that it had activate everything, and it is listed now under https://github.com/gap-packages/Digraphs/settings/installations -- but there is nothing you can do there other than to review and change for which repositories it is active (that's normal and the same for every integration). I'd expect further configuration and settings to be accessible via a page specific to Azure Pipelines, but I know nothing about that.

**Comment by james-d-mitchell** [comment]
Thanks for the explanations and your help @fingolfin it’s much appreciated. I suspect that the part where the pipeline can be enabled is on a page linked to the (non existent) MS account for the gap-packages organisation, so it looks like this won’t work. 

I really just want to have some CI up and running again for Digraphs and Semigroups, which is critical. I’m genuinely open to any suggestions about possible ways forward. I’ve done something in this PR that would work for us, but can’t now progress within the gap-packages organisation.

 If anyone has any suggestions about how to move on this issue then please let me know.

**Comment by wilfwilson** [comment]
I'll quickly try to hack something together with GitHub actions right now.

**Comment by james-d-mitchell** [comment]
> I'll quickly try to hack something together with GitHub actions right now.

I wouldn’t bother if I was you @wilfwilson, what I’ve done here works, and there’s no practical reason that it can’t be enabled for Digraphs, I just don’t have sufficient privileges to enable it, and it seems that no one with those privileges is willing to enable it ( possibly for some perfectly valid reasons that I just don’t know)

**Comment by james-d-mitchell** [comment]
An alternative solution is that we simply transfer ownership of Digraphs and Semigroups to an organization or individual willing to enable azure pipelines. It’s our code after all, I don’t see why we can’t enable whatever we want. Again there might be perfectly good reasons not to enable things inside the gap-package organization, but I don’t know what they are (and I increasingly don’t care)

**Comment by fingolfin** [comment]
Several points:
- I am sorry for taking time to respond to you, but look, it's weekend, I am doing this while my family is waiting for me to finally come down so we can take a stroll.
- I am absolutely willing to enable Azure Pipelines support for your, and AFAICT already did so; but to make it clear, the account Microsoft wanted to force me to create was for my *personal* email and GitHub Account. I'd be perfectly happy to create an MS account for `gap-packages`, but that's not an option. They even claim that they already have accounts for several of my email addresses (all the academic ones) which I actually found shocking; but when I tried to select those, it then went into an error loop. I am willing to do a lot, but MS wants all kinds of things from me (e.g. birthdates) and access, and I just don't feel comfortable doing that. Honestly, I don't feel like the bad guy here.
- What makes you think that MS account is needed to configure Azure Pipelines? Have you used it before? If so (e.g. on your personal account or on another GitHub org), it should be straight forward to adjust the relevant admin URLs to `gap-packages/Digraphs` (usually the USER/REPO is just part of the URL); you could paste that here and I could try to access it
- of course you are also welcome to move these packages to your own GitHub org! I am not holding you hostage. It's not my fault that GitHub has no alternative setting between "enable full access to everything" and "basically can do nothing but play with existing stuff"; nor that MS for some reason apparently started to force MSN account creation on people who want (or in this case: not want but willing to help and thus try anyway) to access their services. Frankly, I find that super hostile from them. Every other CI provider I interacted with that integrates with GitHub is happy to let me "sign in with GitHub" (Travis, CircleCI, Cirrus, GitHub Actions (of course), AppVeyor, ...) -- and in fact, a year ago, Azure Pipelines was one of them. I don't know why you insist on using Azure Pipelines; "possibly for some perfectly valid reasons that I just don’t know" ;-) -- but if that's your choice, I respect it! But please also respect my unwillingness to grant MS full access to my *personal* data and GitHub account

But really: I thought we'd moved past the stage were you attribute malice or bad will to my actions or that of other GAP devs?

**Comment by fingolfin** [comment]
BTW I just tried again: went to the https://dev.azure.com/jdm3/jdm3/_build/results?buildId=21&view=results URL you provided above; clicked on "Sign In" in the top right. It (again) offers me a "Sign in with GitHub" button. If I select that, it tells me:
> Looks like you already have an account with us
> The following emails in your GitHub profile are already accounts with us. Choose one to use.
> If you're using Azure for your work or school, select one of the following.

It shows me a list of addresses I never ever could have used with them, despite their claim. Anyway, no matter which option I choose, it ends up asking me to create a new account -- what's the point of a "Sign in with GitHub" then?

**Comment by fingolfin** [comment]
After this user-hostile experience with Azure Pipelines, added to them require full write access to repositories (apparently so that one can use their GUI editor for the pipelines config), and the fact that they offer fewer parallel jobs than GitHub Actions (just 10, vs 20 -- resp. 60 if one is an education user), I sure know that I won't consider using Azure Pipelines for my own projects for the foreseeable future.

Anywya, MS now shows me this:
> This site is temporarily unavailable
> This site is temporarily unavailable due to maintenance. Please try again later

So I'll now go out and enjoy the sunny Saturday. If anybody has a hint on how to get past the MS login nonsense, I'll be happy to try again later.

(BTW, I do have an MSN account, with a separate email address, for Skype; I tried logging in with that, it also fails; presumably due to that "maintenance". Anyway, I don't feel comfortable associating that with my GitHub account.

There are other gap-packages admins, by the way -- @alex-konovalov and @ChrisJefferson are even local, perhaps one of them already has an MS account and/or less scruples about creating one with personal data; perhaps try prodding them?

**Comment by fingolfin** [comment]
Also @stevelinton

**Comment by james-d-mitchell** [comment]
@fingolfin I'm not attributing malice or bad will to anyone especially not you, I am genuinely very grateful that you've taken the time to try to help with this, and wasn't expecting you to answer immediately (on the weekend or any other time). I resent having to spend any time redoing our CI (this resentment is aimed squarely at travis-ci, not anyone else), and I don't want @wilfwilson or anyone else have to waste additional time doing this again.   

When I set up azure pipeline for `libsemigroups` and in my personal fork of `Digraphs`, I had to click some button on an azure devops page, apparently I already have an MSN account because our university uses their services for something. This was essentially trivial, but it seems you had a rather different experience. 

I tried (several times over a 24 hour period) to find (substituting various parts of urls, and searching within my azure account) the corresponding page for `gap-packages/Digraphs` and eventually came to the conclusion that either it doesn't exist or I don't have access to it. 

I'm going to close this PR, we'll find some alternative arrangement, please no one waste any more time on this.

**Comment by fingolfin** [comment]
@james-d-mitchell I feel you; sorry for snapping at your :-( and yeah I am really upset with Travis. Zero warning? Come on

**Pull request closed without merging**
