### PR TITLE
Is hamiltonian digraph

### PR DESCRIPTION
**Pull request by le27**
Adds a function called IsHamiltonianDigraph which checks if a given digraph is hamiltonian

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Julius agreed to look at this too, and squash-merge if he's happy.

**Comment by ChrisJefferson** [comment]
I'm just jumping in as a separate, interested reader.

I feel you should mention in the docs that uses `O(DigraphNrVertices(g)!)` space and time.

Also, while any algorithm for hamiltonian digraph will use `O(DigraphNrVertices(g)!)`, you can do quite a bit better than this is you want to -- depending on how hard you want to try. It would be nice at least to switch to only using `O(DigraphNrVertices(g))` space by doing a depth-first search (which could also terminate early as soon as it found a path).

**Comment by james-d-mitchell** [comment]
Thanks @chrisjefferson, it'd be good if we could improve the complexity as Chris indicates.

**Comment by wilfwilson** [comment]
Why was this closed?

**Comment by james-d-mitchell** [comment]
I think because @le27 opened a new pull request with the same functionality.

**Pull request closed without merging**
