### PR TITLE
Added PetersenGraph function, along with exmpl file family

### PR DESCRIPTION
**Pull request by MTWhyte**
This pull request adds a function which returns the PetersenGraph, and introduces a set of files "exmpl.*" for adding more graph examples in the future.

### CODE REVIEW

**Comment by wilfwilson** [comment]
Can you please use the name `examples` rather than `exmpl`?  I also wonder if there are other 'examples' in the package that would be better located in this new file – perhaps `JohnsonDigraph`? Perhaps you could have a look.

**Comment by james-d-mitchell** [comment]
I've been using the name `exmpl` in the `mutable` PR, and have rearranged much of the code (into different files), it'd probably be best if @MTWhyte doesn't make too many changes in this PR, otherwise it'll be a nightmare to merge `mutable` later.

**Comment by wilfwilson** [comment]
Okay, in that case I would still urge us to change the name at some later point after the merge. I think it's unhelpful to miss out the vowels.

**Comment by james-d-mitchell** [comment]
You know I have an unreasonable dislike of vowels, but I'm happy to rename the file too. I'm guessing that you won't be a fan of `cnstr` either :(

**Comment by wilfwilson** [comment]
`cnstr`... ouch!

**Comment by james-d-mitchell** [comment]
You mean: ch!

**Comment by MTWhyte** [comment]
I remember seeing a list of examples, when I added PetersenGraph to the documentation.

In `z-chap2.xml`, there is:

`  <Section><Heading>Standard examples</Heading>
    <#Include Label="ChainDigraph">
    <#Include Label="CompleteDigraph">
    <#Include Label="CompleteBipartiteDigraph">
    <#Include Label="CompleteMultipartiteDigraph">
    <#Include Label="CycleDigraph">
    <#Include Label="EmptyDigraph">
    <#Include Label="JohnsonDigraph">
    <#Include Label="PetersenGraph">
  </Section>`

I shall migrate all of these to the exmpl files.

**Comment by james-d-mitchell** [comment]
Please don't move any @MTWhyte, see the comments above!

**Comment by MTWhyte** [comment]
Ah right, I will leave as is then, but I’ll keep those listed in mind for the future.

**Pull request merged**
