### PR TITLE
Modernize ac_find_gap.m4

### PR DESCRIPTION
**Pull request by fingolfin**
* drop CONFIGNAME support
* make it possible to compile against future GAP releases with
  compatibility mode turned off

### CODE REVIEW

**Comment by fingolfin** [comment]
BTW I based this on stable-0.13, so if you'd rather merge this there, it's trivial to retarget this PR.

**Comment by wilfwilson** [comment]
@james-d-mitchell I merged this without talking to you, hope that's alright, but I noticed this in the README which is now out of date somehow:

> If you installed GAP on several architectures, you must execute the configure/make step for each of the architectures. You can either do this immediately after configuring and compiling GAP itself on this architecture, or alternatively (when using version 4.5 of GAP or newer) set the environment variable CONFIGNAME to the name of the configuration you used when compiling GAP before running ./configure. Note however that your compiler choice and flags (environment variables CC and CFLAGS) need to be chosen to match the setup of the original GAP compilation. For example you have to specify 32-bit or 64-bit mode correctly!

**Comment by james-d-mitchell** [comment]
No problem, I'm happy for you to merge things without talking to me! 

What's the correct advice for the README now?

**Comment by wilfwilson** [comment]
I don't know what needs to be done to make it correct, that's why mostly I've brought it to your attention. But certainly the stuff about `CONFIGNAME` should be removed. I've no idea about any of this compilation stuff really.

**Pull request merged**
