### PR TITLE
utils: fix DIGRAPHS_Dir

### PR DESCRIPTION
**Pull request by james-d-mitchell**
Resolves Issue #206.

### CODE REVIEW

**Comment by wilfwilson** [comment]
Could you restart the AppVeyor test? This PR surely can't have affected it, so it's probably just a random failure.

**Comment by james-d-mitchell** [comment]
I'm not so sure, did you look at the appveyor log?

**Comment by james-d-mitchell** [comment]
I restarted in any case...

**Comment by wilfwilson** [comment]
I looked at the log, but couldn't immediately make sense of it. In any case, if it recurs we can look more closely :)

**Comment by james-d-mitchell** [comment]
Failed again

**Comment by wilfwilson** [comment]
Yep, really annoying. It's only when it gets to the extreme tests, after a lot of reading (using `DIGRAPHS_Dir` has already been done.

**Comment by wilfwilson** [comment]
I think that the AppVeyor failure is unrelated to this PR. It's failing here:
```
########> Diff in /home/appveyor/gap/pkg/digraphs/tst/extreme/attr.tst:31
# Input is:
gr := ReadDigraphs(Concatenation(DIGRAPHS_Dir(),
                                    "/data/symmetric-closure.ds6.gz"),
                      DigraphFromDiSparse6String,
                      1);
# Expected output:
<digraph with 46656 vertices, 120245 edges>
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `DigraphFromDiSparse6String' on 1 argume\
nts
The 1st argument is 'fail' which might point to an earlier problem

########

```
But a few lines before it is successfully doing:
```
gap> gr := ReadDigraphs(Concatenation(DIGRAPHS_Dir(),
>                                     "/digraphs-lib/extreme.d6.gz"), 1);
```
And (surely) there's a problem with `DIGRAPHS_Dir()` in the first bit if and only if there's a problem with it in the second bit.

So I think this must be one of those annoying GAP-Windows problems which we battle with (GAP on Windows is weird with forking, which happens when you read a file I think).

I think poking it once a twice more will hopefully get AppVeyor to pass (I'm running it https://ci.appveyor.com/project/wilfwilson/digraphs/builds/25364607 at the moment) - if it does I propose merging.

**Comment by wilfwilson** [comment]
I'm confident that this will pass now.

**Comment by james-d-mitchell** [comment]
Thanks @wilfwilson

**Pull request merged**
