### PR TITLE
Improve DigraphColouring

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This PR implements the Welsh-Powell algorithm for digraph colouring. This implementation is almost always as good as the previous one (in terms of the number of colours required), and is faster (approx.
4 times faster on `DigraphRemoveLoops(RandomDigraph(10000, 0.1)))`.

### CODE REVIEW

**Comment by wilfwilson** [comment]
Nice. Do you think it's faster because you implemented it better, or because it's an inherently faster algorithm?

I'll be happy to merge it, but I do have one request: could you update the documentation for `DigraphColouring` to mention the name of the algorithm? Currently it says quite generically that it uses a greedy algorithm, but now it would be nice to be more specific now that we can be.

**Comment by james-d-mitchell** [comment]
Good idea I’ll do this tomorrow

**Comment by james-d-mitchell** [comment]
@wilfwilson on second reflection, I wonder if it might not be a good idea to have `DigraphGreedyColouring`, `DigraphWelshPowellColouring` and so on. Given that we have an implementation of the standard greedy algorithm, it seems a shame to throw it away, given that there are some cases when it gives a better colouring than the new version. What do you think?

**Comment by james-d-mitchell** [comment]
@wilfwilson I'd propose to keep `DigraphColouring`, and use the version of the algorithm which gives the "best" colouring in the most cases. So, currently, that'd be the Welsh-Powell.

**Comment by wilfwilson** [comment]
@james-d-mitchell Sounds good!

**Comment by james-d-mitchell** [comment]
@wilfwilson I've finished this now. I decided to go in a slightly different direction. I changed to make `DigraphGreedyColouring` for a digraph and an ordering of its vertices, the main function. This way we can get the old behaviour by doing:

~~~~
DigraphGreedyColouring(D, [1 .. DigraphNrVertices(D)]);
~~~~

and the new behaviour by doing:

~~~~
DigraphGreedyColouring(D); # or
DigraphGreedyColouring(D,. DigraphWelshPowellOrder); # or
DigraphGreedyColouring(D,. DigraphWelshPowellOrder(D)); # or
~~~~

Let me know if spot any issues!

**Comment by james-d-mitchell** [comment]
Nuts, thought I did everything

**Comment by james-d-mitchell** [comment]
I just thought of something else to add to this, so please don't merge it yet.

**Comment by james-d-mitchell** [comment]
On second thoughts, I have nothing further to add. Merge if happy @wilfwilson

**Pull request merged**
