### PR TITLE
Allow rational numbers as the second argument of RandomDigraph

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This small PR allows the use of rationals in addition to floats for the second argument of `RandomDigraph`.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
I've updated it! I just removed the `float` from the error message.

**Comment by wilfwilson** [comment]
Thanks @james-d-mitchell! Unfortunately now some tests that tested the old message which are failing Travis.

**Comment by james-d-mitchell** [comment]
Oops will fix tomorrow

**Comment by james-d-mitchell** [comment]
@wilfwilson hopefully fixed now.

**Pull request merged**
